name: advocatus
description: "App institucional para abogados y clientes COLEMEX"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^17.2.4
  
  share_plus: ^10.1.2
  path_provider: ^2.1.5

  # 🎨 Iconos y diseño
  cupertino_icons: ^1.0.8

  # 🌐 Navegación externa
  url_launcher: ^6.2.5

  # 📁 Selector de archivos multiplataforma (Web compatible)
  file_picker: 10.0.0

  # 📷 Cámara y galería
  image_picker: ^1.0.4

  # 🔗 Conexión HTTP y multipart
  http: ^1.1.0
  http_parser: ^4.0.2

  # 💾 Preferencias locales
  shared_preferences: ^2.0.9

  # 📦 Gestión de estado
  provider: ^6.1.1

  # 📍 Geolocalización
  geolocator: ^10.1.0
  geocoding: ^2.1.0

  # 🗺️ Mapas interactivos
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  flutter_map_dragmarker: ^6.0.0

  # 🔑 Permisos
  permission_handler: ^11.3.1

  # 🌍 Internacionalización
  intl: ^0.19.0

  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # 🔥 GENERADOR DE ICONO
  flutter_launcher_icons: ^0.13.1

# 🔥 CONFIGURACIÓN DEL ICONO
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/iconos/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/iconos/
    - assets/fondos/